export enum DietType {
  KETO = 'KETO',
  VEGAN = 'VEGAN',
  VEGETARIAN = 'VEGETARIAN',
  PALEO = 'PALEO',
  MEDITERRANEAN = 'MEDITERRANEAN',
  GLUTEN_FREE = 'GLUTEN_FREE',
  DAIRY_FREE = 'DAIRY_FREE',
  LOW_CARB = 'LOW_CARB',
  HIGH_PROTEIN = 'HIGH_PROTEIN',
  LOW_FAT = 'LOW_FAT',
  PESCATARIAN = 'PESCATARIAN',
  WHOLE30 = 'WHOLE30',
}
